image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install development dependencies
    init: |
      mamba env create -f dev/conda.yml -p dev/env
      
  - name: Install library for development
    init: | 
      pip install -ve .

  - name: Activate dev env
    command: |
      source activate dev/env