image:
  file: .gitpod.Dockerfile

tasks:
  - name: Build Docker image
    init: |
      docker pull quay.io/biocontainers/hapcut2:1.3.3--hb0d9459_3
      docker build -t hapcut2_mec_solver .
      
  - name: Install development dependencies
    init: |
      pip install -v -r dev/requirements.txt
      
  - name: Install library for development
    init: | 
      pip install -ve .

  - name: Log in to Docker Hub
    command: |
      echo $DOCKER_HUB_TOKEN | docker login -u jzhang0246 --password-stdin
