image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install HapCUT2
    init: |
      docker pull quay.io/biocontainers/hapcut2:1.3.3--hb0d9459_3
      
  - name: Install development dependencies
    init: |
      pip install -v -r dev/requirements.txt
      
  - name: Install library for development
    init: | 
      pip install -ve .