name: Build and test Docker image

on: [push]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build -t hapcut2_mec_solver .
    - name: Run tests
      run: |
        docker run --rm  hapcut2_mec_solver tests/test.sh